/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.diamondmarket.users.api;

import com.diamondmarket.users.model.Response;
import com.diamondmarket.users.model.User;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.springframework.http.HttpHeaders;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-02-17T15:10:28.385Z")

@Api(value = "user", description = "the user API")
public interface UserApi {

	@ApiOperation(value = "Create user", notes = "This can only be done by the logged in user.", response = Response.class, tags = {
			"user", })
	@ApiResponses(value = { @ApiResponse(code = 201, message = "successful operation", response = Response.class),
			@ApiResponse(code = 400, message = "Invalid data", response = Response.class) })
	@ApiImplicitParams({ @ApiImplicitParam(name = "correlationId", value = "Correlation ID", paramType = "header"),
			@ApiImplicitParam(name = "ApplicationLabel", value = "Application label", paramType = "header") })

	@RequestMapping(value = "/user", produces = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<Response> createUser(@RequestHeader HttpHeaders httpHeaders,
			@ApiParam(value = "Created user object", required = true) @Valid @RequestBody User body);

	@ApiOperation(value = "Delete user", notes = "This can only be done by the logged in user.", response = Response.class, tags = {
			"user", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "User deleted successfully", response = Response.class),
			@ApiResponse(code = 400, message = "Invalid username supplied", response = Response.class),
			@ApiResponse(code = 404, message = "User not found", response = Response.class) })
	@ApiImplicitParams({ @ApiImplicitParam(name = "correlationId", value = "Correlation ID", paramType = "header"),
			@ApiImplicitParam(name = "ApplicationLabel", value = "Application label", paramType = "header") })
	@RequestMapping(value = "/user", produces = { "application/json" }, method = RequestMethod.DELETE)
	ResponseEntity<Response> deleteUser(@RequestHeader HttpHeaders httpHeaders,
			@ApiParam(value = "The user that needs to be deleted", required = true) @RequestParam(value="userId", required=true) String userId);

	@ApiOperation(value = "Get user by userId", notes = "", response = Response.class, tags = { "user", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation", response = Response.class),
			@ApiResponse(code = 400, message = "Invalid userId supplied", response = Response.class),
			@ApiResponse(code = 404, message = "User not found", response = Response.class) })
	@ApiImplicitParams({ @ApiImplicitParam(name = "correlationId", value = "Correlation ID", paramType = "header"),
			@ApiImplicitParam(name = "ApplicationLabel", value = "Application label", paramType = "header") })

	@RequestMapping(value = "/user", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<Response> getUserById(@RequestHeader HttpHeaders httpHeaders,
			@ApiParam(value = "", required = true) @RequestParam(value="userId", required=true) String userId);

	@ApiOperation(value = "Logs user into the system", notes = "", response = Response.class, tags = { "user", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation", response = Response.class),
			@ApiResponse(code = 400, message = "Invalid username/password supplied", response = Response.class) })
	@ApiImplicitParams({ @ApiImplicitParam(name = "correlationId", value = "Correlation ID", paramType = "header"),
			@ApiImplicitParam(name = "ApplicationLabel", value = "Application label", paramType = "header") })

	@RequestMapping(value = "/user/login", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<Response> loginUser(@RequestHeader HttpHeaders httpHeaders,
			@NotNull @ApiParam(value = "The user name for login", required = true) @RequestParam(value = "username", required = true) String username,
			@NotNull @ApiParam(value = "The password for login in clear text", required = true) @RequestParam(value = "password", required = true) String password);

	@ApiOperation(value = "Updated user", notes = "This can only be done by the logged in user.", response = Response.class, tags = {
			"user", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "User updated successfully", response = Response.class),
			@ApiResponse(code = 400, message = "Invalid user supplied", response = Response.class) })
	@ApiImplicitParams({ @ApiImplicitParam(name = "correlationId", value = "Correlation ID", paramType = "header"),
			@ApiImplicitParam(name = "ApplicationLabel", value = "Application label", paramType = "header") })

	@RequestMapping(value = "/user", produces = { "application/json" }, method = RequestMethod.PUT)
	ResponseEntity<Response> updateUser(@RequestHeader HttpHeaders httpHeaders,
			@ApiParam(value = "Updated user object", required = true) @Valid @RequestBody User body);

}
